// Mock data for development/testing when MongoDB is not available
export const mockDevices = [
  {
    _id: "0",
    name: "iPhone 14 Pro",
    brand: "Apple",
    modelSlug: "iphone-14-pro",
    category: "phone",
    image: "https://via.placeholder.com/300x300?text=iPhone+14+Pro",
  },
  {
    _id: "1",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    modelSlug: "iphone-15-pro-max",
    category: "phone",
    image: "https://via.placeholder.com/300x300?text=iPhone+15+Pro+Max",
  },
  {
    _id: "2",
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    modelSlug: "samsung-galaxy-s24",
    category: "phone",
    image: "https://via.placeholder.com/300x300?text=Galaxy+S24",
  },
  {
    _id: "3",
    name: "MacBook Pro 16",
    brand: "Apple",
    modelSlug: "macbook-pro-16",
    category: "laptop",
    image: "https://via.placeholder.com/300x300?text=MacBook+Pro+16",
  },
  {
    _id: "4",
    name: "Dell XPS 13",
    brand: "Dell",
    modelSlug: "dell-xps-13",
    category: "laptop",
    image: "https://via.placeholder.com/300x300?text=Dell+XPS+13",
  },
  {
    _id: "5",
    name: "iPad Pro 12.9",
    brand: "Apple",
    modelSlug: "ipad-pro-12-9",
    category: "tablet",
    image: "https://via.placeholder.com/300x300?text=iPad+Pro+12.9",
  },
  {
    _id: "6",
    name: "Samsung Galaxy Tab S9",
    brand: "Samsung",
    modelSlug: "samsung-galaxy-tab-s9",
    category: "tablet",
    image: "https://via.placeholder.com/300x300?text=Galaxy+Tab+S9",
  },
  {
    _id: "7",
    name: "Google Pixel 8",
    brand: "Google",
    modelSlug: "google-pixel-8",
    category: "phone",
    image: "https://via.placeholder.com/300x300?text=Pixel+8",
  },
  {
    _id: "8",
    name: "OnePlus 12",
    brand: "OnePlus",
    modelSlug: "oneplus-12",
    category: "phone",
    image: "https://via.placeholder.com/300x300?text=OnePlus+12",
  },
];

export const mockPrices = [
  {
    _id: "p0a",
    deviceId: "0",
    platform: "OLX",
    price: 65000,
    condition: "Excellent",
    location: "Karachi",
    sellerName: "Tech Store",
    url: "https://olx.com.pk",
    description: "iPhone 14 Pro 256GB, like new condition",
  },
  {
    _id: "p0b",
    deviceId: "0",
    platform: "Cashify",
    price: 68000,
    condition: "Good",
    location: "Lahore",
    sellerName: "Cashify",
    url: "https://cashify.pk",
    description: "iPhone 14 Pro with warranty",
  },
  {
    _id: "p0c",
    deviceId: "0",
    platform: "eBay",
    price: 72000,
    condition: "Excellent",
    location: "Islamabad",
    sellerName: "eBay Seller",
    url: "https://ebay.com",
    description: "Brand new iPhone 14 Pro",
  },
  {
    _id: "p1",
    deviceId: "1",
    platform: "OLX",
    price: 85000,
    condition: "Excellent",
    location: "Karachi",
    sellerName: "Tech Store",
    url: "https://olx.com.pk",
    description: "iPhone 15 Pro Max 256GB, like new condition",
  },
  {
    _id: "p2",
    deviceId: "1",
    platform: "Cashify",
    price: 88000,
    condition: "Good",
    location: "Lahore",
    sellerName: "Cashify",
    url: "https://cashify.pk",
    description: "iPhone 15 Pro Max with warranty",
  },
  {
    _id: "p3",
    deviceId: "1",
    platform: "eBay",
    price: 92000,
    condition: "Excellent",
    location: "Islamabad",
    sellerName: "eBay Seller",
    url: "https://ebay.com",
    description: "Brand new iPhone 15 Pro Max",
  },
  {
    _id: "p4",
    deviceId: "2",
    platform: "OLX",
    price: 65000,
    condition: "Good",
    location: "Karachi",
    sellerName: "Mobile Shop",
    url: "https://olx.com.pk",
    description: "Samsung Galaxy S24, 6 months old",
  },
  {
    _id: "p5",
    deviceId: "2",
    platform: "Cashify",
    price: 68000,
    condition: "Excellent",
    location: "Lahore",
    sellerName: "Cashify",
    url: "https://cashify.pk",
    description: "Samsung Galaxy S24 with box",
  },
  {
    _id: "p6",
    deviceId: "3",
    platform: "OLX",
    price: 180000,
    condition: "Excellent",
    location: "Karachi",
    sellerName: "Tech Dealer",
    url: "https://olx.com.pk",
    description: "MacBook Pro 16 M3 Max, 1 year old",
  },
  {
    _id: "p7",
    deviceId: "3",
    platform: "Cashify",
    price: 185000,
    condition: "Good",
    location: "Lahore",
    sellerName: "Cashify",
    url: "https://cashify.pk",
    description: "MacBook Pro 16 with AppleCare",
  },
];

